site_name: My Docs
theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - content.code.annotate
  icon:
    annotation: material/plus-circle-outline

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences